config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope module: 'public' do
    root to: 'home#index'
    get 'about_us', to: 'home#about_us'
    get 'yumans', to: 'home#yumans'
    get 'researchers', to: 'home#researchers'
    get 'projects', to: 'home#projects'
    get 'repositories', to: 'home#repositories'
    get 'graphs', to: 'home#graphs'
    get 'bibliographic_search_engine', to: 'search_engine#bibliographic', as: :bibliographic_search_engine
    get 'lexico_search_engine', to: 'search_engine#lexico', as: :lexico_search_engine
    get "alphabet", to: 'search_engine#alphabet', as: :alphabet_lexico_search_engine
  end

  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  namespace :admin do
    get "dashboard", to: 'dashboard#index'
    resources :carousel
    resources :users do 
      get 'edit_password'
      patch 'update_password'
    end
    resources :projects
    resources :repositories
    resources :bibliographic_files do
      get "versions", to: "bibliographic_files#versions"
      get "researchers", to: "bibliographic_files#researchers"
      post "add_researcher", to: "bibliographic_files#add_researcher"
      post "remove_researcher", to: "bibliographic_files#remove_researcher"
    end
    resources :lexico_files do
      get "alphabet", to: "lexico_files#alphabet"
    end
    resources :alphabets
    resources :languages
    resources :researchers do
      get 'user_researcher', on: :new
    end
  end
end

app/models/researcher.rb
# frozen_string_literal: true

class Researcher < ApplicationRecord
  has_one_attached :image

  belongs_to :user, optional: true
end

app/controllers/admin/researchers_controller.rb
# frozen_string_literal: true

module Admin
  class ResearchersController < BaseController
    before_action :set_researcher, only: %i[show edit update destroy]

    def index
      @researchers = Researcher.all
    end

    def new
      @researcher = Researcher.new
    end

    def edit; end

    def show; end

    def user_researcher
      @users = User.all
    end

    def create
      @researcher = if params[:researcher].nil?
                      new_user_researcher
                    else
                      Researcher.new(researcher_params)
                    end

      if @researcher.save
        redirect_to  admin_researchers_path, notice: 'Se ha agregado el investigador'
      else
        render :new, status: :unprocessable_entity
      end
    end

    def update
      if @researcher.update(researcher_params)
        redirect_to  admin_researchers_path, notice: 'Se ha actualizado el investigador exitosamente'
      else
        render :edit, status: :unprocessable_entity
      end
    end

    private

    def set_researcher
      @researcher = Researcher.find(params[:id])
    end

    def researcher_params
      params.fetch(:researcher).permit(
        :id, :academic_description, :main_language, :main_language_level,
        :user_id, :image, :first_name, :last_name
      )
    end

    def new_user_researcher
      user = User.find(params[:user_id])

      Researcher.new(
        first_name: user.first_name,
        last_name: user.last_name
      )
    end
  end
end

app/views/admin/researchers/_form.html.erb
<%= form_with model: @researcher, url: url do |form| %>
  <div class="mb-3">
    <%= form.label "Nombre", class: "form-label" %>
    <%= form.text_field :first_name, class: "form-control" %>  
  </div>
  <div class="mb-3">
    <%= form.label "Apellido", class: "form-label" %>
    <%= form.text_field :last_name, class: "form-control" %>  
  </div>
  <div class="row g-3 mb-3">
    <div class="col-6">
      <%= form.label "Lengua principal", class: "form-label" %>
      <%= form.select :main_language, Language.all.map(&:name), { include_blank: "- lengua -"}, {:class => "form-select"}  %>
    </div> 
    <div class="col-6">
      <%= form.label "Nivel de lengua que estudia", class: "form-label" %>
      <%= form.select :main_language_level, n1_levels, { include_blank: "- Nivel -"}, {:class => "form-select"}  %>
    </div>	
  </div>
  <div class="mb-3">
    <%= form.label "Descripción académica", class: "form-label" %>
    <%= form.text_area :academic_description, class: "form-control", rows: "6"%>
  </div>
  <div class="mb-3">
    <%= form.label "Foto de usuario", class: "form-label" %>
    <%= form.file_field :image, direct_upload: true, class: "form-control" %>
  </div>

  <div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
    <%= form.submit "Guardar", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/admin/researchers/_researcher.html.erb
<%= form_with model: @researcher, url: url do |form| %>

	<%= form.collection_select :user_id, User.all, :id, :name_with_initial, {}, {:class => "form-select"} %>


	<div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
    <%= form.submit "Agregar usauario como investigador", class: "btn btn-primary" %>
  </div>

<% end %>

app/views/admin/researchers/edit.turbo_stream.erb
<%= turbo_stream.replace "remote_modal" do %>
  <%= render partial: "shared/form_modal", 
	locals: { 
		url: admin_researcher_path(@researcher),
		partial: 'admin/researchers/form',
		title: 'Editar investigador',
		size: 'modal-lg'
	} %>
<% end %>

app/views/admin/researchers/index.html.erb
<p class="h2 pb-3 text-center">Índice de investigadores</p>

<table class="table table-striped fs-4">  
	<tr>
		<th scope="col">Nombre</th>
		<th scope="col">Lengua</th>
		<th scope="col">Nivel</th>
		<th></th>
	</tr>
	<% @researchers.each do |researcher|  %>
		<tr>
			<td><%= link_to full_name(researcher), admin_researcher_path(researcher), "data-controller": "turbo" %></td>
			<td><%= researcher.main_language %></td>
			<td><%= researcher.main_language_level %></td>
			<td>
				<%= link_to edit_admin_researcher_path(researcher), "data-controller": "turbo" do %>
					<i class="bi bi-files" style="color:black"></i>
				<% end %>
      </td>
		</tr>
	<% end %>
</table>

<div class="text-center">
	<%= link_to "Crear nuevo investigador", new_admin_researcher_path, "data-controller": "turbo", class: 'btn btn-primary mx-2'%>
	<%= link_to "Crear investigador a base de usuario existente", user_researcher_new_admin_researcher_path, "data-controller": "turbo", class: ' mx-2 btn btn-primary '%>
</div>

app/views/admin/researchers/new.turbo_stream.erb
<%= turbo_stream.replace "remote_modal" do %>
  <%= render partial: "shared/form_modal", 
	locals: { 
		url: admin_researchers_path,
		partial: 'admin/researchers/form',
		title: 'Crear nuevo investigador',
		size: 'modal-lg'
	} %>
<% end %>

app/views/admin/researchers/show.turbo_stream.erb
<%= turbo_stream.replace "remote_modal" do %>
  <%= render partial: "shared/form_modal", 
	locals: { 
		url: admin_bibliographic_files_path,
		partial: 'shared/card',
		title: 'Perfil del investigador',
		size: 'modal-fullscreen'
	} %>
<% end %>

app/views/admin/researchers/user_researcher.turbo_stream.erb
<%= turbo_stream.replace "remote_modal" do %>
  <%= render partial: "shared/form_modal", 
	locals: { 
		url: admin_researchers_path,
		partial: 'admin/researchers/researcher',
		title: 'Seleccionar usuario para crear investigador'
	} %>
<% end %>