config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope module: 'public' do
    root to: 'home#index'
    get 'about_us', to: 'home#about_us'
    get 'yumans', to: 'home#yumans'
    get 'researchers', to: 'home#researchers'
    get 'projects', to: 'home#projects'
    get 'repositories', to: 'home#repositories'
    get 'graphs', to: 'home#graphs'
    get 'bibliographic_search_engine', to: 'search_engine#bibliographic', as: :bibliographic_search_engine
    get 'lexico_search_engine', to: 'search_engine#lexico', as: :lexico_search_engine
    get "alphabet", to: 'search_engine#alphabet', as: :alphabet_lexico_search_engine
  end

  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  namespace :admin do
    get "dashboard", to: 'dashboard#index'
    resources :carousel
    resources :users do 
      get 'edit_password'
      patch 'update_password'
    end
    resources :projects
    resources :repositories
    resources :bibliographic_files do
      get "versions", to: "bibliographic_files#versions"
      get "researchers", to: "bibliographic_files#researchers"
      post "add_researcher", to: "bibliographic_files#add_researcher"
      post "remove_researcher", to: "bibliographic_files#remove_researcher"
    end
    resources :lexico_files do
      get "alphabet", to: "lexico_files#alphabet"
    end
    resources :alphabets
    resources :languages
    resources :researchers do
      get 'user_researcher', on: :new
    end
  end
end

app/views/shared/_bibliographic_file.html.erb
<%# TODO: Refactorizar esto con desktop, mobile y bibi_search... %>

<div id="<%= dom_id bibliographic_file %>">
  <tr>
    <td class="text-center">
      <%= image_tag("public/drawings/#{bibliographic_file.free_lock == true ? 'lock' : 'unlock'}.svg", width: 10) %>
      <% if bibliographic_file.pdf %>
        <i class="bi bi-file-pdf"></i>
      <% end %>
      <% if bibliographic_file.ms %>
        <i>MS</i>
      <% end %>
    </td>
    <td><%= bibliographic_file.id %></td>
    <td><%= bibliographic_file.year %></td>
    <td>
      <b class="pb-3"><%= resercher_full_name(bibliographic_file) %></b>
      <br />
      <br />
      <% bibliographic_file.secondary_authors.each do |author|%>
        <p class="m-0"><%= author.full_name %></p>
      <% end %>
    </td>
    <td><%= bibliographic_file.gender %></td>
    <td><%= bibliographic_file.language_y %></td>
    <td><%= bibliographic_file.language_y2 %></td>
    <% if bibliographic_file.has_access && bibliographic_file.acces_link %>
      <td><%= link_to bibliographic_file.title, bibliographic_file.acces_link %></td>
    <% else %>
      <td><%= bibliographic_file.title %></td>
    <% end %>
    
    <% if bibliographic_file.new_b_data == true %>
      <td><%= bibliographic_file.data %></td>
    <% else %>
      <td><%= bibliographic_file.b_data %></td>
    <% end %>

    <td><%= bibliographic_file.n1.try(:capitalize) %></td>
    <td><%= bibliographic_file.n2.try(:capitalize) %></td>
    <td><%= bibliographic_file.document_language %></td>
    <td><%= bibliographic_file.base %></td>
    <% if current_page?(admin_bibliographic_files_path) %>
      <td>
        <%= link_to edit_admin_bibliographic_file_path(bibliographic_file), "data-controller": "turbo" do %>
          <i class="bi bi-files" style="color:black"></i>
        <% end %>
        <%= link_to admin_bibliographic_file_versions_path(bibliographic_file), "data-controller": "turbo" do %>
          <i class="bi bi-book" style="color:black"></i>
        <% end %>
        <%= link_to admin_bibliographic_file_researchers_path(bibliographic_file), "data-controller": "turbo" do %>
          <i class="bi bi-person" style="color:black"></i>
        <% end %>
      </td>
    <% end %>
  </tr>
</div>

app/views/shared/_bibliographic_search.html.erb
<div class="px-4">
	<div class="card mb-3 px-0">
	<div class="card-header bg-primary">
		Filtros
	</div>
	<div class="card-body">
			<%= search_form_for @q, url: url do |f| %>					
				<%= f.label "Busqueda" %>
				<%= f.text_field :title_or_b_data_cont, class: 'form-control' %>

				<%= f.label "Nivel de lengua", class: "mt-3 mb-1" %>
				<%= f.select :n1_matches, n1s, { include_blank: true }, {class: "form-select" } %>
				
				<%= f.label "Lengua", class: "mt-3 mb-1" %>
				<div class="mb-3">
				<% Language.all.map(&:name).each do |lang| %>
					<%= lang %>
					<%= f.check_box :language_y_in, {multiple: true, class: "form-check-input me-4"}, lang, nil %>
				<% end %>
				</div>
				

				<%= f.submit "Busqueda avanzada", class: 'btn btn-primary mb-3' %>
				<%= link_to "Limpiar", request.path, class: "btn btn-light mb-3" %>
			<% end %>
			<p>Hay <%= @results %> resultados </p>
	</div>
	</div>
</div>

<% if current_page?(controller: 'admin/bibliographic_files') %>
	<div class="d-grid gap-2 col-3 mx-auto">
		<%= link_to "Nuevo registro", new_admin_bibliographic_file_path, class: "btn btn-primary", "data-controller": "turbo" %>
	</div>
<% end %>

<% if device == "desktop" %>
  <%= render partial: 'shared/desktop' %>
<% else %>
	<%= render partial: 'shared/mobile' %>
<% end %>

<div class="d-flex justify-content-center">
	<%== pagy_bootstrap_nav(@pagy) %>
</div>

app/views/shared/_card.html.erb
<%= render(CardComponent.new(
			name: full_name(@researcher), 
			image_url: @researcher.image,
			description: @researcher.academic_description,
			language: @researcher.main_language,
			level: @researcher.main_language_level,
			email: @researcher.contact_email,
			website_link: @researcher.website_link
))  %>

app/views/shared/_desktop.html.erb
<%# TODO: Eliminar version movil y hacer el media query %>
<table class="table">
	<thead>
		<tr>
			<th scope="col"></th>
			<th scope="col"><%= sort_link(@q, :id, "Id", default_order: :asc) %></th>
			<th scope="col"><%= sort_link(@q, :year, "Año", default_order: :asc) %></th>
			<th scope="col">Investigador</th>
			<th scope="col"><%= sort_link(@q, :gender, "Género", default_order: :asc) %></th>
			<th scope="col"><%= sort_link(@q, :language_y, "Lengua primaria", default_order: :asc) %></th>
			<th scope="col"><%= sort_link(@q, :language_y2, "Lengua secundaria", default_order: :asc) %></th>
			<th scope="col">Título</th>
			<th scope="col">Datos B</th>
			<th scope="col"><%= sort_link(@q, :n1, "Nivel de lengua primario", default_order: :asc) %></th>
			<th scope="col"><%= sort_link(@q, :n2, "Nivel de lengua secundario", default_order: :asc) %></th>
			<th scope="col"><%= sort_link(@q, :document_language, "Idioma", default_order: :asc) %></th>
			<th scope="col"><%= sort_link(@q, :base, "Base", default_order: :asc) %></th>
		</tr>
	</thead>
	<tbody>
		<% @files.each do |file| %>
			<%= render partial: "shared/bibliographic_file", object: file %>
		<% end %>
	</tbody>
</table>

app/views/shared/_form.html.erb
<div class="py-3">
  <%= form_with(model: @bibliographic_file, url: url) do |form| %>
    <div class="error_explanation">
      <% if @bibliographic_file.errors.any? %>
        <div style="color: red">
          <h2><%= pluralize(@bibliographic_file.errors.count, "error") %> prohibited this bibliographic_file from being saved:</h2>
          <ul>
            <% @bibliographic_file.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
    </div>
    <div class="row g-3 mb-3">
      <div class="col-6">
        <%= form.label "Tipo de documento" %>
        <%= form.select :document_type, document_types, {}, {:class => "form-select"} %>
      </div>
      <div class="col-6">
        <%= form.label "Lenguaje del documento" %>
        <%= form.text_field :document_language, class: "form-control" %>
      </div>
    </div>
    <div class="row g-3 mb-3">
      <div class="col-6">
        <%= form.label "Primer lenguaje" %>
        <%= form.text_field :language_y, class: "form-control" %>
      </div>
      <div class="col-6">
        <%= form.label "Segundo lenguaje" %>
        <%= form.text_field :language_y2, class: "form-control" %>
      </div>
    </div>
    <div class="row g-3 mb-3">
      <div class="col-4">
        <%= form.label "Nombre del investigador" %>
        <%= form.text_field :researcher_first_name, class: "form-control" %>
      </div>
      <div class="col-4">
        <%= form.label "Apellido del investigador" %>
        <%= form.text_field :researcher_last_name, class: "form-control" %>
      </div>
      <div class="col-4">
        <%= form.label "Genero" %>
        <%= form.text_field :gender, class: "form-control" %>
      </div>
    </div>
    <div class="row g-3 mb-3">
      <div class="col-6">
        <%= form.label "Titulo" %>
        <%= form.text_field :title, class: "form-control" %>
      </div>
      <div class="col-3">
        <%= form.label "Año" %>
        <%= form.number_field :year, class: "form-control" %>
      </div>
      <div class="col-3">
        <%= form.label "MS" %>
        <%= form.text_field :ms, class: "form-control" %>
      </div>
    </div>
    <br />
    <hr />
    <br />
    <legend class="text-center">Datos B</legend>
    <div class="row g-3 mb-3">
      <div class="col-4">
        <%= form.label "journal_bookname" %>
        <%= form.text_field :journal_bookname, class: "form-control" %>
      </div>
      <div class="col-4">
        <%= form.label "Editorial" %>
        <%= form.text_field :publisher, class: "form-control" %>
      </div>
      <div class="col-4">
        <%= form.label "Ciudad" %>
        <%= form.text_field :city_country, class: "form-control" %>
      </div>
    </div>
    <div class="row g-3 mb-3">
      <div class="col-4">
        <%= form.label "editor_record" %>
        <%= form.text_field :editor_record, class: "form-control" %>
      </div>
      <div class="col-4">
        <%= form.label "Volumen" %>
        <%= form.text_field :volume, class: "form-control" %>
      </div>
      <div class="col-4">
        <%= form.label "Numero de volumen" %>
        <%= form.text_field :volume_number, class: "form-control" %>
      </div>
    </div>
    <div class="row g-3 mb-3">
      <div class="col-4">
        <%= form.label "isbn" %>
        <%= form.text_field :isbn, class: "form-control" %>
      </div>
      <div class="col-4">
        <%= form.label "issn" %>
        <%= form.text_field :issn, class: "form-control" %>
      </div>
      <div class="col-4">
        <%= form.label "doi" %>
        <%= form.text_field :doi, class: "form-control" %>
      </div>
    </div>
    <br />
    <hr />
    <br />
    <div class="row g-3 mb-3">
      <div class="col-4">
        <%= form.label "Pais" %>
        <%= form.text_field :country, class: "form-control" %>
      </div>
      <div class="col-4">
        <%= form.label "Base" %>
        <%= form.text_field :base, class: "form-control"  %>
      </div>
      <div class="col-4">
        <%= form.label "Link de acceso" %>
        <%= form.text_field :acces_link, class: "form-control" %>
      </div>
    </div>
    <div class="row g-3 mb-3">
      <div class="col-4">
        <%= form.label "N1" %>
        <%= form.select :n1, n1s, {include_blank: true}, {:class => "form-select"}  %>
      </div>
      <div class="col-4">
        <%= form.label "N2" %>
        <%= form.select :n2, n1s, {include_blank: true}, {:class => "form-select"}  %>
      </div>
      <div class="col-4">
        <%= form.label "Numero de pagina" %>
        <%= form.number_field :page_number, class: "form-control"  %>
      </div>
    </div>
    <div>
      <%= form.label "free_lock" %>
      <%= form.check_box :free_lock, class: "form-check-input" %>
    </div>
    
    <div class="modal-footer">
      <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
      <%= form.submit "Guardar", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/shared/_form_modal.html.erb
<%= turbo_frame_tag :remote_modal, target: :_top do %>
  <%# Added "data-bs-focus="false"" so slim slect can work inside a modal%>
  <div class="modal fade" data-controller="modal" tabindex="-1" data-bs-focus="false" >
    <div class="modal-dialog <%= defined?(size).nil? ? '' : size %>">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title"><%= title %></h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <%= render partial: partial, locals: { url: url } %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_mobile.html.erb
<% @files.each_with_index do |file, index| %> 
	<table class="table table-bordered <%= index.even? ? "table-secondary" : ""%>">
		<tbody>
			<tr>
				<th>Candado:</th>
				<td>si</td>
			</tr>
			<tr>
				<th>Año</th>
				<td><%= file.year %></td>
			</tr>
			<tr>
				<th>Investigador</th>
				<td><%= resercher_full_name(file) %></td>
			</tr>
			<tr>
				<th>Género</th>
				<td><%= file.gender %></td>
			</tr>
			<tr>
				<th>Lengua primaria</th>
				<td><%= file.language_y %></td>
			</tr>
			<tr>
				<th>Lengua secundario</th>
				<td><%= file.language_y2 %></td>
			</tr>
			<tr>
				<th>Título</th>
				<td><%= file.title %></td>
			</tr>
			<tr>
				<th>Datos_B</th>
				<td><%= file.b_data %></td>
			</tr>
			<tr>
				<th>Nivel de lengua primario</th>
				<td><%= file.n1 %></td>
			</tr>
			<tr>
				<th>Nivel de lengua secundario</th>
				<td><%= file.n2 %></td>
			</tr>
			<tr>
				<th>Idioma</th>
				<td><%= file.document_language %></td>
			</tr>
			<tr>
				<th>Base</th>
				<td><%= file.base %></td>
			</tr>
		</tbody>
	</table>
<% end %>

	

app/views/shared/_project_card.html.erb
<%= render(ProjectCardComponent.new(
	title: @project.title, 
	body: @project.body,
	image_url: @project.image
)) %>

app/views/shared/_researcher_card.html.erb
<%= render(CardComponent.new(
			name: full_name(@researcher), 
			image_url: @researcher.image,
			description: @researcher.academic_description,
			language: @researcher.main_language,
			level: @researcher.main_language_level
))  %>