config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope module: 'public' do
    root to: 'home#index'
    get 'about_us', to: 'home#about_us'
    get 'yumans', to: 'home#yumans'
    get 'researchers', to: 'home#researchers'
    get 'projects', to: 'home#projects'
    get 'repositories', to: 'home#repositories'
    get 'graphs', to: 'home#graphs'
    get 'bibliographic_search_engine', to: 'search_engine#bibliographic', as: :bibliographic_search_engine
    get 'lexico_search_engine', to: 'search_engine#lexico', as: :lexico_search_engine
    get "alphabet", to: 'search_engine#alphabet', as: :alphabet_lexico_search_engine
  end

  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  namespace :admin do
    get "dashboard", to: 'dashboard#index'
    resources :carousel
    resources :users do 
      get 'edit_password'
      patch 'update_password'
    end
    resources :projects
    resources :repositories
    resources :bibliographic_files do
      get "versions", to: "bibliographic_files#versions"
      get "researchers", to: "bibliographic_files#researchers"
      post "add_researcher", to: "bibliographic_files#add_researcher"
      post "remove_researcher", to: "bibliographic_files#remove_researcher"
    end
    resources :lexico_files do
      get "alphabet", to: "lexico_files#alphabet"
    end
    resources :alphabets
    resources :languages
    resources :researchers do
      get 'user_researcher', on: :new
    end
  end
end

app/models/lexico_file.rb
# frozen_string_literal: true

class LexicoFile < ApplicationRecord
	require 'csv'
	nilify_blanks
	has_paper_trail

	has_one_attached :audio_file, service: :local
	
	belongs_to :alphabet, optional: true
	belongs_to :bibliographic_file, optional: true

	delegate :researcher_first_name, :researcher_last_name, :year, to: :bibliographic_file, allow_nil: true


	def self.ransackable_attributes(auth_object = nil)
		["alphabet", "audio", "author", "bibliographic_file_id", "created_at", "english_word", 
			"id", "language", "page", "provider", "spanish_word", "translated", "updated_at", 
			"word", "year_of_publication"]
	end

	def self.ransackable_associations(auth_object = nil)
    ["versions"]
  end

	def self.to_csv
		lexico_files = all
		CSV.generate do |csv|
			csv << column_names
			lexico_files.each do |lf|
				csv << lf.attributes.values_at(*column_names)
			end
		end
	end

end

app/controllers/admin/lexico_files_controller.rb
# frozen_string_literal: true

module Admin
  class LexicoFilesController < BaseController
    include ActiveStorage::SetCurrent
    before_action :set_lexico_file, only: %i[edit update]
    before_action :set_alphabets

    def index
      @q = LexicoFile.ransack(params[:q])
      @pagy, @files = pagy(@q.result(distinct: true).order("id ASC"))
      @results = @q.result.count
      respond_to do |format|
        format.html
        format.csv { send_data LexicoFile.to_csv, filename: "BULE-#{DateTime.now.strftime("%d%m%Y%H%M")}.csv"}
      end
    end

    def alphabet
      @alphabet = Alphabet.find(params[:alphabet_id])
    end

    def new
      @lexico_file = LexicoFile.new
    end
    
    def edit;end

    def create
			@lexico_file = LexicoFile.new(lexico_params)
			if @lexico_file.save
				redirect_to admin_lexico_files_path, notice: 'Se agrego un nuevo archivo léxico'
			else
				render :new, status: :unprocessable_entity
			end
		end

    def update
      if @lexico_file.update(lexico_params)
        notice = "La ficha léxica se ha actualizado correctamente"
        redirect_to admin_lexico_files_path, notice: notice
      else
        render :edit, status: :unprocessable_entity
      end
    end

    private

    def lexico_params
      params.fetch(:lexico_file).permit(:id, :language, :word, :spanish_word, :english_word, 
        :author, :year_of_publication, :page, :provider, :translated, :audio, :audio_file,
        :bibliographic_file_id, :alphabet_id)
    end
    
    def set_lexico_file
      @lexico_file = LexicoFile.find(params[:id])
    end

    def set_alphabets
      @alphabets = Alphabet.all
    end
  end
end

app/views/admin/lexico_files/_alphabet.html.haml
= markdown(@alphabet.text)

app/views/admin/lexico_files/_form.html.haml
.py-3
  = form_with(model: @lexico_file, url: url) do |form|
    .error_explanation
      - if @lexico_file.errors.any?
        %div{:style => "color: red"}
          %h2
            = pluralize(@lexico_file.errors.count, "error")
            prohibited this lexico_file from being saved:
          %ul
            - @lexico_file.errors.each do |error|
              %li= error.full_message
    .row.g-3.mb-3
      .col-6
        = form.label "Lengua"
        = form.text_field :language, class: "form-control"
      .col-6
        = form.label "Palabra"
        = form.text_field :word, class: "form-control"

    .row.g-3.mb-3
      .col-6
        = form.label "Español"
        = form.text_field :spanish_word, class: "form-control"
      .col-6
        = form.label "Ingles"
        = form.text_field :english_word, class: "form-control"

    .row.g-3.mb-3
      .col-6
        = form.label "Page"
        = form.text_field :page, class: "form-control"
      .col-6
        = form.label "Prestador"
        = form.text_field :provider, class: "form-control"
    .row.g-3.mb-3
      .col-6
        = form.label "Alfabeto"
        = form.select :alphabet_id, @alphabets.collect{|p| [p.name, p.id]}, { include_blank: ""}, {:class => "form-select",}
      .col-3
        = form.label "Traducido"
        = form.check_box :translated, class: "form-check-input"
      .col-3
        = form.label "Audio"
        = form.check_box :audio, class: "form-check-input"
    .row.g-3.mb-3
      = form.label "Subir audio"
      = form.file_field :audio_file, class: "form-control"

    

    .row.g-3.mb-3
      = form.label "Seleccionar archivo bibliografico relacionado"
      = form.select :bibliographic_file_id, BibliographicFile.pluck(:title, :id), {include_blank: true}, {data: { controller: 'slim', slim_target: 'field' } }

      .modal-footer
        %button.btn.btn-secondary{"data-bs-dismiss" => "modal", :type => "button"} Cerrar
        = form.submit "Guardar", class: "btn btn-primary"

app/views/admin/lexico_files/alphabet.turbo_stream.erb
<%= turbo_stream.replace "remote_modal" do %>
  <%= render partial: "shared/form_modal", 
  locals: { 
    url: "",
    partial: 'admin/lexico_files/alphabet',
    title: "Alfabeto",
    size: 'modal-xl'
  } %>
<% end %>

app/views/admin/lexico_files/edit.turbo_stream.erb
<%= turbo_stream.replace "remote_modal" do %>
  <%= render partial: "shared/form_modal", 
  locals: { 
    url: admin_lexico_file_path(@lexico_file),
    partial: 'admin/lexico_files/form',
    title: "Editar archivo #{@lexico_file.id}",
    size: 'modal-xl'
  } %>
<% end %>

app/views/admin/lexico_files/index.html.haml
-# Remover estos y agregarlos en el application html
%script{:src => "https://unpkg.com/@popperjs/core@2"}
%script{:src => "https://unpkg.com/tippy.js@6"}




.row.bg-white.py-5.px-3
  .row.pt-2.bg-white
    .col.my-auto.pb-2
      .h1= "Buscador léxico"
    .col-8
      .text-end
        = link_to "Exportar", admin_lexico_files_path(format: 'csv'), class: "btn btn-primary"

  .px-4
    .card.mb-3.px-0
      .card-header.bg-primary
        Filtros
      .card-body
        = search_form_for @q, url: admin_lexico_files_path do |f|
          = f.label "Busqueda"
          = f.text_field :spanish_word_cont, class: 'form-control'
          = f.submit "Buscar", class: 'btn btn-primary mb-3'
          = link_to "Limpiar", request.path, class: "btn btn-light mb-3"

  .d-grid.gap-2.col-3.mx-auto
    = link_to "Nuevo registro léxico", new_admin_lexico_file_path, class: "btn btn-primary", "data-controller": "turbo"

  %table.table{"data-controller" => "tippy"}
    %thead
      %tr
        %th{scope: "col"}= sort_link(@q, :id, "Id", default_order: :asc)
        %th{scope: "col"}= sort_link(@q, :language, "Lenguaje", default_order: :asc)
        %th{scope: "col"}= sort_link(@q, :word, "Palabra", default_order: :asc)
        %th{scope: "col"}= sort_link(@q, :spanish_word, "Español", default_order: :asc)
        %th{scope: "col"}= sort_link(@q, :english_word, "Ingles", default_order: :asc)
        %th{scope: "col"}= sort_link(@q, :bibliographic_file_id, "Archivo Bibliográfico", default_order: :asc)
        %th{scope: "col"}= sort_link(@q, :af, "A.F.", default_order: :asc)
        %th{scope: "col"}= sort_link(@q, :structure, "Estructura", default_order: :asc)
        %th{scope: "col"}= sort_link(@q, :author, "Autor", default_order: :asc)
        %th{scope: "col"}= sort_link(@q, :year_of_publication, "Año de publicación", default_order: :asc)
        %th{scope: "col"}= sort_link(@q, :page, "Página", default_order: :asc)
        %th{scope: "col"}= sort_link(@q, :original_language, "Lengua Original", default_order: :asc)
        %th{scope: "col"}= sort_link(@q, :alphabet_id, "Alfabeto", default_order: :asc)
        %th{scope: "col"}= sort_link(@q, :audio, "Audio", default_order: :asc)
    %tbody
      - @files.each do |file|
        %div{id: "#{dom_id file}"}
          %tr
            %td#tippy= file.id
            %td#tippy{"data-tippy-content"=>"hello"}= file.language 
            %td= file.word 
            %td= file.spanish_word
            %td= file.english_word
            %td= file.bibliographic_file_id
            %td= file.af
            %td= file.structure
            %td= resercher_full_name(file)
            %td= file.year
            %td= file.page
            %td= file.original_language
            - if file.alphabet_id
              %td
                = link_to admin_lexico_file_alphabet_path(file, alphabet_id: file.alphabet_id), "data-controller": "turbo" do
                  = image_tag("feather.svg")
            - else
              %td              
            %td= file.created_at.strftime("%Y-%m-%d")
            - if file.audio == true
              %td= audio_tag  Rails.application.routes.url_helpers.rails_blob_url(file.audio_file, only_path: true ), controls: true, controlslist: "nodownload noplaybackrate"
            - else
              %td
            %td
              = link_to edit_admin_lexico_file_path(file), "data-controller": "turbo" do
                %i.bi.bi-files{style: "color:black"}

            

  %div.pb-1

.d-flex.justify-content-center
  != pagy_bootstrap_nav(@pagy)

app/views/admin/lexico_files/new.turbo_stream.erb
<%= turbo_stream.replace "remote_modal" do %>
  <%= render partial: "shared/form_modal", 
  locals: { 
    url: admin_lexico_files_path,
    partial: 'admin/lexico_files/form',
    title: "Nuevo archivo léxico",
    size: 'modal-xl'
  } %>
<% end %>