config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope module: 'public' do
    root to: 'home#index'
    get 'about_us', to: 'home#about_us'
    get 'yumans', to: 'home#yumans'
    get 'researchers', to: 'home#researchers'
    get 'projects', to: 'home#projects'
    get 'repositories', to: 'home#repositories'
    get 'graphs', to: 'home#graphs'
    get 'bibliographic_search_engine', to: 'search_engine#bibliographic', as: :bibliographic_search_engine
    get 'lexico_search_engine', to: 'search_engine#lexico', as: :lexico_search_engine
    get "alphabet", to: 'search_engine#alphabet', as: :alphabet_lexico_search_engine
  end

  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  namespace :admin do
    get "dashboard", to: 'dashboard#index'
    resources :carousel
    resources :users do 
      get 'edit_password'
      patch 'update_password'
    end
    resources :projects
    resources :repositories
    resources :bibliographic_files do
      get "versions", to: "bibliographic_files#versions"
      get "researchers", to: "bibliographic_files#researchers"
      post "add_researcher", to: "bibliographic_files#add_researcher"
      post "remove_researcher", to: "bibliographic_files#remove_researcher"
    end
    resources :lexico_files do
      get "alphabet", to: "lexico_files#alphabet"
    end
    resources :alphabets
    resources :languages
    resources :researchers do
      get 'user_researcher', on: :new
    end
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :researcher

  enum role: { user: 0, intern: 1, researcher: 2, admin: 3 }

  def name_with_initial
    if first_name.empty?
      email.to_s
    else
      "#{first_name} #{last_name}"
    end
  end
end

app/controllers/admin/users_controller.rb
# frozen_string_literal: true

module Admin
  class UsersController < BaseController
    before_action :set_user, only: %i[show edit edit_password update update_password destroy]
    def index
      @users = User.all
    end

    def new
      @user = User.new
    end

    def edit; end

    def edit_password
      
    end

    def show; end

    def create
      @user = User.new(user_params)
      if @user.save
        redirect_to  admin_users_path, notice: 'Se ha agregado el usuario'
      else
        render :new, status: :unprocessable_entity
      end
    end

    def update
      if @user.update(user_params)
        redirect_to  admin_users_path, notice: 'Se ha actualizado el usuario exitosamente'
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def update_password
      password = params[:user][:password]
      binding.break
      if @user.reset_password(password, password)
        redirect_to  admin_users_path, notice: 'Se ha actualizado la contraseña del usuario exitosamente'
      else
        render :edit, status: :unprocessable_entity
      end
    end

    private

    def set_user
      if params[:id].nil?
        @user = User.find(params[:user_id])
      else
        @user = User.find(params[:id])
      end
    end

    def user_params
      params.fetch(:user).permit(
        :id, :role, :password, :password_confirmation,
        :email, :image, :first_name, :last_name, :website_link
      )
    end
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

module Users
  class ConfirmationsController < Devise::ConfirmationsController
    # GET /resource/confirmation/new
    # def new
    #   super
    # end

    # POST /resource/confirmation
    # def create
    #   super
    # end

    # GET /resource/confirmation?confirmation_token=abcdef
    # def show
    #   super
    # end

    # protected

    # The path used after resending confirmation instructions.
    # def after_resending_confirmation_instructions_path_for(resource_name)
    #   super(resource_name)
    # end

    # The path used after confirmation.
    # def after_confirmation_path_for(resource_name, resource)
    #   super(resource_name, resource)
    # end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

module Users
  class OmniauthCallbacksController < Devise::OmniauthCallbacksController
    # You should configure your model like this:
    # devise :omniauthable, omniauth_providers: [:twitter]

    # You should also create an action method in this controller like this:
    # def twitter
    # end

    # More info at:
    # https://github.com/heartcombo/devise#omniauth

    # GET|POST /resource/auth/twitter
    # def passthru
    #   super
    # end

    # GET|POST /users/auth/twitter/callback
    # def failure
    #   super
    # end

    # protected

    # The path used when OmniAuth fails
    # def after_omniauth_failure_path_for(scope)
    #   super(scope)
    # end
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

module Users
  class PasswordsController < Devise::PasswordsController
    # GET /resource/password/new
    # def new
    #   super
    # end

    # POST /resource/password
    # def create
    #   super
    # end

    # GET /resource/password/edit?reset_password_token=abcdef
    # def edit
    #   super
    # end

    # PUT /resource/password
    # def update
    #   super
    # end

    # protected

    # def after_resetting_password_path_for(resource)
    #   super(resource)
    # end

    # The path used after sending reset password instructions
    # def after_sending_reset_password_instructions_path_for(resource_name)
    #   super(resource_name)
    # end
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

module Users
  class RegistrationsController < Devise::RegistrationsController
    # before_action :configure_sign_up_params, only: [:create]
    # before_action :configure_account_update_params, only: [:update]

    # GET /resource/sign_up
    # def new
    #   super
    # end

    # POST /resource
    # def create
    #   super
    # end

    # GET /resource/edit
    # def edit
    #   super
    # end

    # PUT /resource
    # def update
    #   super
    # end

    # DELETE /resource
    # def destroy
    #   super
    # end

    # GET /resource/cancel
    # Forces the session data which is usually expired after sign
    # in to be expired now. This is useful if the user wants to
    # cancel oauth signing in/up in the middle of the process,
    # removing all OAuth session data.
    # def cancel
    #   super
    # end

    # protected

    # If you have extra params to permit, append them to the sanitizer.
    # def configure_sign_up_params
    #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
    # end

    # If you have extra params to permit, append them to the sanitizer.
    # def configure_account_update_params
    #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
    # end

    # The path used after sign up.
    # def after_sign_up_path_for(resource)
    #   super(resource)
    # end

    # The path used after sign up for inactive accounts.
    # def after_inactive_sign_up_path_for(resource)
    #   super(resource)
    # end
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

module Users
  class SessionsController < Devise::SessionsController
    # before_action :configure_sign_in_params, only: [:create]

    # GET /resource/sign_in
    # def new
    #   super
    # end

    # POST /resource/sign_in
    # def create
    #   super
    # end

    # DELETE /resource/sign_out
    # def destroy
    #   super
    # end

    # protected

    # If you have extra params to permit, append them to the sanitizer.
    # def configure_sign_in_params
    #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
    # end
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

module Users
  class UnlocksController < Devise::UnlocksController
    # GET /resource/unlock/new
    # def new
    #   super
    # end

    # POST /resource/unlock
    # def create
    #   super
    # end

    # GET /resource/unlock?unlock_token=abcdef
    # def show
    #   super
    # end

    # protected

    # The path used after sending unlock password instructions
    # def after_sending_unlock_instructions_path_for(resource)
    #   super(resource)
    # end

    # The path used after unlocking the resource
    # def after_unlock_path_for(resource)
    #   super(resource)
    # end
  end
end

app/helpers/user_helper.rb
# frozen_string_literal: true

module UserHelper
  def blank_name?(user)
    user.first_name.blank? || user.last_name.blank?
  end

  def full_name(user)
    return 'Sin nombre' if blank_name?(user)

    [user.first_name, user.last_name].join(' ')
  end

  def name_initials(user)
    return '' if blank_name?(user)

    user.first_name.first.capitalize + user.last_name.first.capitalize
  end

  def user_first_name(user)
    return user.email if user.first_name.blank?

    user.first_name
  end
end

app/views/admin/users/_form.html.erb
<%= form_with model: @user, url: url do |form| %>
  <div class="mb-3">
    <%= form.label "Nombre", class: "form-label" %>
    <%= form.text_field :first_name, class: "form-control" %>  
  </div>
  <div class="mb-3">
    <%= form.label "Apellido", class: "form-label" %>
    <%= form.text_field :last_name, class: "form-control" %>  
  </div>
	<div class="mb-3">
    <%= form.label "Correo electronico", class: "form-label" %>
    <%= form.text_field :email, class: "form-control" %>  
  </div>
	<div class="mb-3">
    <%= form.label "Rol", class: "form-label" %>
    <%= form.select :role, User.roles.keys.to_a, {}, {:class => "form-select"} %>  
  </div>
  <div class="mb-3">
    <%= form.label "Contraseña", class: "form-label" %>
    <%= form.password_field :password, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label "Confirmar contraseña", class: "form-label" %>
    <%= form.password_field :password_confirmation, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit "Guardar", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/admin/users/_form_edit.html.erb
<%= form_with model: @user, url: url do |form| %>
  <div class="mb-3">
    <%= form.label "Nombre", class: "form-label" %>
    <%= form.text_field :first_name, class: "form-control" %>  
  </div>
  <div class="mb-3">
    <%= form.label "Apellido", class: "form-label" %>
    <%= form.text_field :last_name, class: "form-control" %>  
  </div>
	<div class="mb-3">
    <%= form.label "Correo electronico", class: "form-label" %>
    <%= form.text_field :email, class: "form-control" %>  
  </div>
	<div class="mb-3">
    <%= form.label "Rol", class: "form-label" %>
    <%= form.select :role, User.roles.keys.to_a, {}, {:class => "form-select"} %>  
  </div>
  <div class="actions float-end">
    <%= form.submit "Actualizar", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/admin/users/_form_password.html.erb
<%= form_with model: @user, url: url do |form| %>
  <div class="mb-3">
    <%= form.label "Contraseña", class: "form-label" %>
    <%= form.password_field :password, class: "form-control" %>
  </div>
  <div class="actions">
    <%= form.submit "Guardar", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/admin/users/edit.turbo_stream.erb
<%= turbo_stream.replace "remote_modal" do %>
  <%= render partial: "shared/form_modal", 
	locals: { 
		url: admin_user_path(@user),
		partial: 'admin/users/form_edit',
		title: 'Editar usuario'
	} %>
<% end %>

app/views/admin/users/edit_password.turbo_stream.erb
<%= turbo_stream.replace "remote_modal" do %>
  <%= render partial: "shared/form_modal", 
	locals: { 
		url: admin_user_update_password_path(@user),
		partial: 'admin/users/form_password',
		title: 'Editar usuario'
	} %>
<% end %>

app/views/admin/users/index.html.erb
<p class="h2 pb-3 text-center">Índice de usuarios</p>

<table class="table table-striped fs-4">  
	<tr>
		<th scope="col">Nombre</th>
		<th scope="col">Correo</th>
		<th scope="col">Rol</th>
		<th scope="col">Fecha de creación</th>
		<th></th>
		<th></th>
	</tr>
	<% @users.each do |user|  %>
		<tr>
			<td><%= full_name(user) %></td>
			<td><%= user.email %></td>
			<td><%= user.role %></td>
			<td><%= user.created_at %></td>
			<td>
				<%= link_to edit_admin_user_path(user), "data-controller": "turbo" do %>
					<i class="bi bi-files" style="color:black"></i>
				<% end %>
			</td>
			 <td>
				<%= link_to admin_user_edit_password_path(user), "data-controller": "turbo" do %>
					<%= image_tag("passport.svg", width: 30) %>
				<% end %>
      </td>
		</tr>
	<% end %>
</table>

<div class="text-center">
	<%= link_to "Crear nuevo usuario", new_admin_user_path, "data-controller": "turbo", class: 'btn btn-primary '%>
</div>

app/views/admin/users/new.turbo_stream.erb
<%= turbo_stream.replace "remote_modal" do %>
  <%= render partial: "shared/form_modal", 
	locals: { 
		url: admin_users_path,
		partial: 'admin/users/form',
		title: 'Crear nuevo usuario'
	} %>
<% end %>